[package]
name = "mousemove"
version = "0.1.0"
edition = "2021"

[dependencies]
tide = "0.16.0"

[dependencies.async-std]
version = "1.12.0"
features = ["attributes"]

[dependencies.windows-sys]
version = "0.52"
features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
]